name: Docker Image CI

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: "aurora"

    steps:
      - uses: actions/checkout@v2

      - name: Set PROJECT_VERSION in ENV
        run: |
          echo "PROJECT_VERSION=$(git describe --abbrev=0 --tag)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            itsrennyman/${{ env.PROJECT_NAME }}:latest
            itsrennyman/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}
            docker.pkg.github.com/${{ github.repository }}/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
